/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2018-03-29 08:28:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Collections;
import java.util.Collection;
import code.movieData;
import java.util.Iterator;
import beans.movieModel;
import java.util.List;
import com.database.ConnectionManager;
import com.helper.UserModel;

public final class Recommendation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../tiles/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../tiles/topbar.jsp", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");

	UserModel um= null;
	if(session.getAttribute("USER_MODEL")!=null){
		um=(UserModel)session.getAttribute("USER_MODEL");
	}
		String user=um.getUsername();
		String userid=um.getUserid();
		List list=null;
		try{
		 list = ConnectionManager.getRecommendation(userid);
		}catch(Exception e){
			
		}
// 		for(int i=0;i<list.size();i++){
// 			movieModel mv=new movieModel();
// 			mv=(movieModel)list.get(i);
// 			System.out.println(mv.getTitle());
// 		}
		
		
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("  <div class=\"main-content\">\r\n");
      out.write("  \t<div class=\"container\">\r\n");
      out.write("  \t\t");
      out.write("\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t\t<div class=\"gallery col-lg-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"main-title-head\">\r\n");
      out.write("\t\t\t\t\t\t\t  <h3 class=\"tittle\"><i class=\"glyphicon glyphicon-picture\"></i>Recommended Movies</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"gallery-images\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"course_demo1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <ul id=\"flexiselDemo1\">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t  ");

			for (int i=list.size()-1;i>list.size()/2;i--) {
				movieModel object = (movieModel) list.get(i);
			
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/search.jsp?movname=");
      out.print(object.getTitle());
      out.write('"');
      out.write('>');
      out.print(object.getPoster() );
      out.write("</a>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t ");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t </ul>\r\n");
      out.write("\t\t\t\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t $(window).load(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#flexiselDemo1\").flexisel({\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvisibleItems: 10,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tanimationSpeed: 1000,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tautoPlay: true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tautoPlaySpeed: 3000,    \t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\tpauseOnHover: true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tenableResponsiveBreakpoints: true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tresponsiveBreakpoints: { \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tportrait: { \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tchangePoint:480,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvisibleItems: 2\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}, \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tlandscape: { \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tchangePoint:640,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvisibleItems: 2\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttablet: { \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tchangePoint:768,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvisibleItems: 3\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t });\r\n");
      out.write("\t\t\t\t\t\t\t  </script>\r\n");
      out.write("\t\t\t\t\t\t\t <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/jquery.flexisel.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"course_demo1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <ul id=\"flexiselDemo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  ");

// 								  List list1=null;
// 								 Collections.reverse(list);
			for (int i=list.size()/2;i>=0;i--) {
				movieModel object = (movieModel)list.get(i);
			
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/search.jsp?movname=");
      out.print(object.getTitle());
      out.write('"');
      out.write('>');
      out.print(object.getPoster() );
      out.write("</a>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t </ul>\r\n");
      out.write("\t\t\t\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t $(window).load(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#flexiselDemo\").flexisel({\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvisibleItems: 4,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tanimationSpeed: 1000,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tautoPlay: true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tautoPlaySpeed: 3000,    \t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\tpauseOnHover: true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tenableResponsiveBreakpoints: true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tresponsiveBreakpoints: { \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tportrait: { \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tchangePoint:480,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvisibleItems: 2\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}, \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tlandscape: { \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tchangePoint:640,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvisibleItems: 2\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttablet: { \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tchangePoint:768,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvisibleItems: 3\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t });\r\n");
      out.write("\t\t\t\t\t\t\t  </script>\r\n");
      out.write("\t\t\t\t\t\t\t <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/jquery.flexisel.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");

// 					List list1=ConnectionManager.getGeneresMovies(userid);
					List list1=ConnectionManager.getRecommendedMovies(userid);
					System.out.println("--------------------:"+list.size()+":--------------------");
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"gallery col-lg-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"main-title-head\">\r\n");
      out.write("\t\t\t\t\t\t\t  <h3 class=\"tittle\"><i class=\"glyphicon glyphicon-film\"></i>Genres Wise Recommended Movies</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"gallery-images\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"course_demo1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <ul id=\"flexiselDemo2\">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t  ");

			for (int i=0;i<list1.size()/2;i++) {
				movieModel object = (movieModel)list1.get(i);
			
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/search.jsp?movname=");
      out.print(object.getTitle());
      out.write('"');
      out.write('>');
      out.print(object.getPoster() );
      out.write("</a>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t ");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t </ul>\r\n");
      out.write("\t\t\t\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t $(window).load(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#flexiselDemo2\").flexisel({\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvisibleItems: 10,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tanimationSpeed: 1000,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tautoPlay: true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tautoPlaySpeed: 3000,    \t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\tpauseOnHover: true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tenableResponsiveBreakpoints: true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tresponsiveBreakpoints: { \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tportrait: { \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tchangePoint:480,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvisibleItems: 2\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}, \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tlandscape: { \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tchangePoint:640,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvisibleItems: 2\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttablet: { \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tchangePoint:768,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvisibleItems: 3\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t });\r\n");
      out.write("\t\t\t\t\t\t\t  </script>\r\n");
      out.write("\t\t\t\t\t\t\t <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/jquery.flexisel.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"course_demo1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <ul id=\"flexiselDemo4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  ");

// 								  List list1=null;
// 								 Collections.reverse(list1);
			for (int i=list1.size()/2;i<list1.size();i++) {
				movieModel object = (movieModel)list1.get(i);
			
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/search.jsp?movname=");
      out.print(object.getTitle());
      out.write('"');
      out.write('>');
      out.print(object.getPoster() );
      out.write("</a>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t </ul>\r\n");
      out.write("\t\t\t\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t $(window).load(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#flexiselDemo4\").flexisel({\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvisibleItems: 4,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tanimationSpeed: 1000,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tautoPlay: true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tautoPlaySpeed: 3000,    \t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\tpauseOnHover: true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tenableResponsiveBreakpoints: true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tresponsiveBreakpoints: { \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tportrait: { \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tchangePoint:480,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvisibleItems: 2\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}, \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tlandscape: { \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tchangePoint:640,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvisibleItems: 2\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttablet: { \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tchangePoint:768,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvisibleItems: 3\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t });\r\n");
      out.write("\t\t\t\t\t\t\t  </script>\r\n");
      out.write("\t\t\t\t\t\t\t <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/jquery.flexisel.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../tiles/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
